import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {baiJamjuree} from '~/components/ui/fonts'
import '~/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={baiJamjuree.className}>{children}</body>
    </html>
  )
}
