import type {Metadata} from 'next'
import {fontSans} from '~/components/ui/fonts'
import {cn} from '~/lib/utils'
import RootProviders from '~/providers'
import '~/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable,
        )}
      >
        <RootProviders>{children}</RootProviders>
      </body>
    </html>
  )
}
